### PR TITLE
Register vault factory at aludel launch

### PR DESCRIPTION
**Pull request by joehquak**
Aludel initialises with msg.sender as owner (aludel factory)

Launch function then does the following:
*sets vault factory
*adds bonus tokens
*sets owner to correct address

### CODE REVIEW

**Comment by itirabasso** [comment]
you should remove `ownerAddress` from `AludelInitializationParams`

**Comment by joehquak** [comment]
> you should remove `ownerAddress` from `AludelInitializationParams`

we still need it for PowerSwitch etc, it's still used in the aludel initialisation

**Comment by itirabasso** [comment]
that was a fast reply!

i was about to delete the comment after I realized what you mentioned

**Comment by joehquak** [comment]
> that was a fast reply!
> 
> i was about to delete the comment after I realized what you mentioned

im duck ninja

**Comment by joehquak** [comment]
I've updated this so we don't need to duplicate the ownerAddress in params and launch

**Pull request merged**
